# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bitsplitter < Formula
  desc "CLI subnet calculator for IPv4 and IPv6"
  homepage "https://github.com/justinsautter/bitsplitter"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justinsautter/BitSplitter/releases/download/v1.0.0/BitSplitter_darwin_amd64.tar.gz"
      sha256 "0d1d85cd0af670c5b7988a8cfb3bd7e9da75d6180b19ce1e8c08270ccdde2848"

      define_method(:install) do
        bin.install "bitsplitter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justinsautter/BitSplitter/releases/download/v1.0.0/BitSplitter_darwin_arm64.tar.gz"
      sha256 "aafe54082626d1fb3eefbbe176cb254c4de7145212d93beccefd4bb59a876b33"

      define_method(:install) do
        bin.install "bitsplitter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinsautter/BitSplitter/releases/download/v1.0.0/BitSplitter_linux_amd64.tar.gz"
      sha256 "2e94a945a11fb8dbc232c9d5e2d39eaad78f16259d9d3c89f6b4d0e6b46efa28"
      define_method(:install) do
        bin.install "bitsplitter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinsautter/BitSplitter/releases/download/v1.0.0/BitSplitter_linux_arm64.tar.gz"
      sha256 "0fd6e31eb00267a3fda47b8d07cbcdb1882a560fa2f9dfcf737e9007c60a28ff"
      define_method(:install) do
        bin.install "bitsplitter"
      end
    end
  end

  test do
    system "#{bin}/bitsplitter", "192.168.1.0/24"
  end
end
