# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bitsplitter < Formula
  desc "CLI subnet calculator for IPv4 and IPv6"
  homepage "https://github.com/justinsautter/bitsplitter"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justinsautter/BitSplitter/releases/download/v1.1.0/BitSplitter_darwin_amd64.tar.gz"
      sha256 "65e0d9212eff76d2758a98f1b71affeb60d8c8a952a1f83b20b7593cea3673c8"

      define_method(:install) do
        bin.install "bitsplitter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justinsautter/BitSplitter/releases/download/v1.1.0/BitSplitter_darwin_arm64.tar.gz"
      sha256 "14c292222da140c02dd3e6d182523e029889a6514ac7e500eef0ff0c2c074b15"

      define_method(:install) do
        bin.install "bitsplitter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinsautter/BitSplitter/releases/download/v1.1.0/BitSplitter_linux_amd64.tar.gz"
      sha256 "a5806249c727ac4ebd177441db3e51e174c2b67d3dd98c3df4fa4b7b41f2388d"
      define_method(:install) do
        bin.install "bitsplitter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinsautter/BitSplitter/releases/download/v1.1.0/BitSplitter_linux_arm64.tar.gz"
      sha256 "e0569c7f6806c0e72ea163c0b9be1531f08a66f57a832884c890d868dc45fabf"
      define_method(:install) do
        bin.install "bitsplitter"
      end
    end
  end

  test do
    system "#{bin}/bitsplitter", "192.168.1.0/24"
  end
end
